import Head from "next/head"
import Image from "next/image"
import Link from "next/link"
import styles from "../styles/Home.module.css"
import { useSession, getSession, signOut } from "next-auth/react"
import axios from "axios"
import { useEffect, useState } from "react"

export default function Home() {
  const { data: session } = useSession()
  const [email, setEmail] = useState("")

  useEffect(() => {
    const res = localStorage.getItem("email")
    console.log("email from localsto", res)
    setEmail(res)
    // fetchProfile(email)
  }, [])

  const fetchProfile = async (email) => {
    console.log("fetchProfile email param", email)

    const res = await axios.get(`http://localhost:5000/api/users/${email}`)
    const userProfile = await res.data
    console.log("userProfile", userProfile)
  }

  function handleSignout() {
    signOut()
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? User({ session, handleSignout }) : Guest()}
    </div>
  )
}

// Guest
function Guest() {
  return (
    <main className="container py-20 mx-auto text-center">
      <h3 className="text-4xl font-bold">Guest Homepage</h3>
      <div className="flex justify-center">
        <Link href={"/login"}>
          <a className="px-10 py-1 mt-5 bg-indigo-500 rounded-sm text-gray-50">
            Sign In
          </a>
        </Link>
      </div>
    </main>
  )
}

// Authorize User
function User({ session, handleSignout, users }) {
  console.log("sessionnn", session)
  console.log("users at index.js", users)
  return (
    <main className="container py-20 mx-auto text-center">
      <h3 className="text-4xl font-bold">Authorize User Homepage</h3>

      <div className="details">
        <h5>Unknown- {session.user.name}</h5>
        <h5>Unknown - {session.user.email}</h5>
      </div>

      <div className="flex justify-center">
        <button
          className="px-10 py-1 mt-5 rounded-sm bg-gray-50"
          onClick={handleSignout}
        >
          Sign Out
        </button>
      </div>

      <div className="flex justify-center">
        <Link href={"/profile"}>
          <a className="px-10 py-1 mt-5 bg-indigo-500 rounded-sm text-gray-50">
            Profile Page
          </a>
        </Link>
      </div>
    </main>
  )
}

export async function getServerSideProps({ req }) {
  const session = await getSession({ req })

  if (!session) return { redirect: { destination: "/login", permanent: false } }

  return {
    props: { session },
  }
}
